#!/bin/bash

exe=$(which rustfmt)

if [ -n "$exe" ]
then
    # field separator to the new line
    IFS=$'\r\n'

    for line in $(git status -s)
    do
        # if added or modified
        if [[ $line == A* || $line == M* ]]
        then
            filename=${line:3}
            # check file extension
            if [[ $filename =~ \.rs$ ]]
            then
                echo "$(pwd)/${filename}"
                # format file
                rustfmt $(pwd)/${filename}
                # add changes
                git add $(pwd)/${filename}
            fi
        fi
    done

else
    echo "rustfmt was not found"
fi

cargo check
cargo clippy -- -D warnings
