name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Build
        run: cargo build --release && strip target/release/tldr && mv target/release/tldr target/release/tldr_amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/tldr_amd64
          token: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Build
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/tldr.exe
          token: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            targets: x86_64-apple-darwin
            components: rustfmt, clippy

      - name: Build for mac
        run: cargo build --all --release && strip target/release/tldr && mv target/release/tldr target/release/tldr_darwin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/tldr_darwin
          token: ${{ secrets.GITHUB_TOKEN }}
